name 'newbox'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'All Rights Reserved'
description 'Installs/Configures newbox'
long_description 'Installs/Configures newbox'
version '0.1.0'
chef_version '>= 14.0'

depends 'user'
depends 'git_user'
